name: CI - InmoGestión

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          cd inmogestion-frontend
          npm install

      - name: Build project
        run: |
          cd inmogestion-frontend
          npm run build

      - name: Run tests
        run: |
          cd inmogestion-frontend
          npm test

      - name: Run linter
        run: |
          cd inmogestion-frontend
          npm run lint
